import jsPDF from 'jspdf';
import 'jspdf-autotable';

// Base64 encoded MyBookmark logo
const LOGO_BASE64 = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAyAAAAIVCAIAAACm0gyVAAAAIGNIUk0AAHomAACAhAAA+gAAAIDoAAB1MAAA6mAAADqYAAAXcJy6UTwAAAAGYktHRAD/AP8A/6C9p5MAAAAJcEhZcwAAAEgAAABIAEbJaz4AAAAHdElNRQfqAgYFIAsgPaE5AAAAd3RFWHRSYXcgcHJvZmlsZSB0eXBlIGlwdGMAAGiJY2BgYGRAABKzMCSBaMowMDAw/ww+qQW1/0AYP1pYGFg4k0D0AACw/gZOPP+R6wAAAAJiS0dEAAHdihOkAAAAB3RJTUUH6gIGBSALID2hOQAAB1JJREFUOE7t3AFSU0EYh+HLpgcIICADEQQREAEBERDUREAQ';

export const generateReadingReportPDF = async (
  childName,
  schoolName,
  teacherName,
  parentName,
  sessions,
  startDate,
  endDate
) => {
  try {
    const doc = new jsPDF();
    
    // Add logo (left side, smaller size)
    const logoWidth = 35;
    const logoHeight = 23; // Maintaining aspect ratio
    const logoX = 15;
    const logoY = 10;
    
    doc.addImage(LOGO_BASE64, 'PNG', logoX, logoY, logoWidth, logoHeight);
    
    // School name and title (right of logo)
    const textX = logoX + logoWidth + 5;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(schoolName, textX, logoY + 8);
    
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.text('Official Reading Log', textX, logoY + 15);
    
    // Horizontal line separator
    doc.setLineWidth(0.5);
    doc.line(15, logoY + logoHeight + 5, 195, logoY + logoHeight + 5);
    
    let yPosition = logoY + logoHeight + 15;
    
    // Student and report information
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    
    const infoStartY = yPosition;
    doc.text(`Student: ${childName}`, 15, infoStartY);
    doc.text(`Teacher: ${teacherName}`, 15, infoStartY + 6);
    doc.text(`Report Period: ${startDate} - ${endDate}`, 15, infoStartY + 12);
    
    yPosition = infoStartY + 20;
    
    // Summary statistics
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Reading Summary', 15, yPosition);
    
    yPosition += 8;
    
    const totalSessions = sessions.length;
    const totalMinutes = sessions.reduce((sum, s) => sum + (s.minutes || 0), 0);
    const uniqueBooks = new Set(sessions.map(s => s.book?.title).filter(Boolean)).size;
    
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Total Reading Sessions: ${totalSessions}`, 15, yPosition);
    doc.text(`Total Minutes Read: ${totalMinutes}`, 15, yPosition + 6);
    doc.text(`Books Read: ${uniqueBooks}`, 15, yPosition + 12);
    
    yPosition += 22;
    
    // Detailed reading log table
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Detailed Reading Log', 15, yPosition);
    
    yPosition += 5;
    
    // Prepare table data
    const tableData = sessions.map(session => {
      const date = new Date(session.timestamp).toLocaleDateString();
      const bookTitle = session.book?.title || 'Unknown Book';
      const author = session.book?.author || 'Unknown Author';
      const minutes = session.minutes || 0;
      const pages = session.pages || '-';
      
      return [date, bookTitle, author, `${minutes} min`, pages];
    });
    
    // Create table
    doc.autoTable({
      startY: yPosition,
      head: [['Date', 'Book Title', 'Author', 'Minutes', 'Pages']],
      body: tableData,
      theme: 'grid',
      headStyles: { 
        fillColor: [102, 51, 153], // Purple color matching your brand
        textColor: 255,
        fontStyle: 'bold',
        fontSize: 9
      },
      bodyStyles: {
        fontSize: 8
      },
      columnStyles: {
        0: { cellWidth: 25 },
        1: { cellWidth: 60 },
        2: { cellWidth: 50 },
        3: { cellWidth: 25 },
        4: { cellWidth: 20 }
      },
      margin: { left: 15, right: 15 }
    });
    
    // Get the final Y position after table
    const finalY = doc.lastAutoTable.finalY + 15;
    
    // Verification signature section
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Verified by: ${parentName} (Parent/Guardian)`, 15, finalY);
    doc.text(`Date: ${new Date().toLocaleDateString()}`, 15, finalY + 6);
    
    // Signature line
    doc.setLineWidth(0.3);
    doc.line(15, finalY + 15, 80, finalY + 15);
    doc.setFontSize(8);
    doc.text('Parent/Guardian Signature', 15, finalY + 19);
    
    // Footer with MyBookmark branding
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by MyBookmark - Family Reading Tracker', 15, pageHeight - 10);
    doc.text(`Report generated on ${new Date().toLocaleDateString()}`, 15, pageHeight - 6);
    
    // Save the PDF
    const fileName = `${childName.replace(/\s+/g, '-')}-Reading-Report-${new Date().toISOString().split('T')[0]}.pdf`;

    // Footer (draw on every page)
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const totalPages = doc.getNumberOfPages();

    for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.text(
    "Generated with OurBookmark — ourbookmark.com",
    pageWidth / 2,
    pageHeight - 10,
    { align: "center" }
  );
    doc.setTextColor(0);
}

    // Save the PDF (keep this after the loop)
    doc.save(fileName);
    
    return { success: true, fileName };
    
  } catch (error) {
    console.error('Error generating PDF:', error);
    throw new Error('Failed to generate PDF report');
  }
};
